#!/bin/sh

set -efu

HEALTH_CHECK_IP="${1:-127.0.0.1}"
HEALTH_CHECK_PORT="${2:-9000}"

env -i REDIRECT_STATUS=true \
    SCRIPT_NAME=/ping \
    SCRIPT_FILENAME=/ping \
    REQUEST_METHOD=GET \
    cgi-fcgi -bind -connect \
    "${HEALTH_CHECK_IP}:${HEALTH_CHECK_PORT}" \
    | grep -e pong >/dev/null
