name: Docker Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.php_version }}-composer${{ matrix.composer_version }}-${{ matrix.server }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["fpm", "rr"]
        php_version: ["8.1", "8.2", "8.3", "8.4", "8.5"]
        composer_version: ["2"]
        platforms: ["linux/amd64,linux/arm64/v8"]
        include:
          - php_version: "8.5"
            latest: "true"
    env:
      TEST_TAG: ${{ github.repository }}:test
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Docker meta (base)
        id: meta-base
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            clevyr/php
            ghcr.io/clevyr/php
          flavor: latest=false
          tags: |
            # {{major}}.{{minor}}-composer{{major}}-{{server}}-base
            type=semver,pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }}-${{ matrix.server }}-base,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-{{server}}-base
            type=semver,enable=${{ matrix.composer_version == '2' }},pattern={{major}}.{{minor}},suffix=-${{ matrix.server }}-base,value=${{ matrix.php_version }}.0
            # {{major}}-{{server}}-base
            type=semver,enable=${{ matrix.composer_version == '2' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},suffix=-${{ matrix.server }}-base,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-composer{{major}}-base (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }}-base,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-base (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},suffix=-base,value=${{ matrix.php_version }}.0
            # {{major}}-base (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},suffix=-base,value=${{ matrix.php_version }}.0

      - name: Docker meta (onbuild)
        id: meta-onbuild
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            clevyr/php
            ghcr.io/clevyr/php
          flavor: latest=false
          tags: |
            # latest (FPM only)
            type=raw,enable=${{ matrix.latest == 'true' && matrix.server == 'fpm' }},value=latest
            # {{major}}.{{minor}}-composer{{major}}-{{server}}-onbuild
            type=semver,pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }}-${{ matrix.server }}-onbuild,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-composer{{major}}-{{server}}
            type=semver,pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }}-${{ matrix.server }},value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-{{server}}-onbuild
            type=semver,enable=${{ matrix.composer_version == '2' }},pattern={{major}}.{{minor}},suffix=-${{ matrix.server }}-onbuild,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-{{server}}
            type=semver,enable=${{ matrix.composer_version == '2' }},pattern={{major}}.{{minor}},suffix=-${{ matrix.server }},value=${{ matrix.php_version }}.0
            # {{major}}-composer{{major}}-{{server}}
            type=semver,enable=${{ (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},suffix=-composer${{ matrix.composer_version }}-${{ matrix.server }},value=${{ matrix.php_version }}.0
            # {{major}}-{{server}}-onbuild
            type=semver,enable=${{ matrix.composer_version == '2' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},suffix=-${{ matrix.server }}-onbuild,value=${{ matrix.php_version }}.0
            # {{major}}
            type=semver,enable=${{ matrix.composer_version == '2' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-composer{{major}}-onbuild (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }}-onbuild,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-composer{{major}} (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},suffix=-composer${{ matrix.composer_version }},value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}}-onbuild (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},suffix=-onbuild,value=${{ matrix.php_version }}.0
            # {{major}}.{{minor}} (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' }},pattern={{major}}.{{minor}},value=${{ matrix.php_version }}.0
            # {{major}}-composer{{major}} (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},suffix=-composer${{ matrix.composer_version }},value=${{ matrix.php_version }}.0
            # {{major}} (FPM only)
            type=semver,enable=${{ matrix.composer_version == '2' && matrix.server == 'fpm' && (matrix.latest_major == 'true' || matrix.latest == 'true') }},pattern={{major}},value=${{ matrix.php_version }}.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          pull: true
          load: true
          file: Dockerfile.${{ matrix.server }}
          tags: ${{ env.TEST_TAG }}
          build-args: |
            COMPOSER_VERSION=${{ matrix.composer_version }}
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test nginx config
        if: matrix.server == 'fpm'
        run: docker run --rm -i "$TEST_TAG" nginx -t
      - name: Test php-fpm config
        if: matrix.server == 'fpm'
        run: docker run --rm -i "$TEST_TAG" php-fpm -tt
      - name: Test RoadRunner
        if: matrix.server == 'rr'
        run: docker run --rm -i "$TEST_TAG" rr --version
      - name: Test commands exist
        run: docker run --rm -i "$TEST_TAG" which composer install-php-extensions clevyr-build

      - name: Build and Push (base)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          file: Dockerfile.${{ matrix.server }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          build-args: |
            COMPOSER_VERSION=${{ matrix.composer_version }}
            PHP_VERSION=${{ matrix.php_version }}
          target: base
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push (onbuild)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          file: Dockerfile.${{ matrix.server }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.meta-onbuild.outputs.tags }}
          labels: ${{ steps.meta-onbuild.outputs.labels }}
          build-args: |
            COMPOSER_VERSION=${{ matrix.composer_version }}
            PHP_VERSION=${{ matrix.php_version }}
          target: onbuild
          cache-from: type=gha
          cache-to: type=gha,mode=max
